- name: Create runit dir
  file:
    state: 'directory'
    path: '/etc/service/{{ apm_service_name }}'

- name: Create runit script
  template:
    src: 'apm-runit-script.j2'
    dest: '/etc/service/{{ apm_service_name }}/run'
    mode: '0755'
