---
# handlers file for newrelic

- name: restart {{ sysmond_service_name }}
  shell: >
    /bin/true
  notify: 'restart {{ sysmond_service_name }} {{ newrelic_init_system }}'

- name: restart {{ sysmond_service_name }} upstart
  service:
    name: '{{ sysmond_service_name }}'
    state: 'restarted'

- name: restart {{ sysmond_service_name }} runit
  shell: >
    /bin/{{ newrelic_skip_notify }} || (sleep 5 && sv restart {{ sysmond_service_name }})

- name: reload {{ sysmond_service_name }}
  shell: >
    /bin/true
  notify: 'reload {{ sysmond_service_name }} {{ newrelic_init_system }}'

- name: reload {{ sysmond_service_name }} upstart
  service:
    name: '{{ sysmond_service_name }}'
    state: 'reloaded'

- name: reload {{ sysmond_service_name }} runit
  shell: >
    /bin/{{ newrelic_skip_notify }} || (sleep 5 && sv reload {{ sysmond_service_name }})
